// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transaction.sql

package db

import (
	"context"
	"database/sql"
)

const deposit = `-- name: Deposit :one
INSERT INTO transactions (account_id, transaction_type, amount, status, reference_id)
VALUES ($1, 'deposit', $2, 'pending', $3)
RETURNING id, account_id, transaction_type, amount, status, reference_id
`

type DepositParams struct {
	AccountID   int32  `json:"account_id"`
	Amount      string `json:"amount"`
	ReferenceID string `json:"reference_id"`
}

type DepositRow struct {
	ID              int32                   `json:"id"`
	AccountID       int32                   `json:"account_id"`
	TransactionType NullTransactionTypeEnum `json:"transaction_type"`
	Amount          string                  `json:"amount"`
	Status          sql.NullString          `json:"status"`
	ReferenceID     string                  `json:"reference_id"`
}

func (q *Queries) Deposit(ctx context.Context, arg DepositParams) (DepositRow, error) {
	row := q.db.QueryRowContext(ctx, deposit, arg.AccountID, arg.Amount, arg.ReferenceID)
	var i DepositRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionType,
		&i.Amount,
		&i.Status,
		&i.ReferenceID,
	)
	return i, err
}
